app/main/forms.py
from flask_login import current_user
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed, FileField
from PIL import Image
from wtforms import PasswordField, StringField, SubmitField
from wtforms.validators import EqualTo, InputRequired, Length, ValidationError

from app.models import User


class EditAvatarForm(FlaskForm):
    avatar = FileField('Update Avatar',
                       validators=[InputRequired(), FileAllowed(['jpg', 'png', 'jpeg'])])
    submit = SubmitField('Update')


class EditUsernameForm(FlaskForm):
    username = StringField('Username',
                           validators=[
                               InputRequired(), Length(min=3, max=20)
                           ])
    submit = SubmitField('Update')

    def validate_username(self, username):
        if username.data != current_user.username:
            users = User.query.filter_by(username=username.data).all()
            if len(users):
                raise ValidationError('Username has already been taken.')


class EditPasswordForm(FlaskForm):
    password = PasswordField('Password',
                             validators=[
                                 InputRequired(), Length(min=8, max=50)
                             ])
    new_password = PasswordField('New Password',
                                 validators=[
                                     InputRequired(),
                                     Length(min=8, max=50),
                                     EqualTo('confirm_new_password',
                                             'New Passwords must match.')
                                 ])
    confirm_new_password = PasswordField('Confirm New Password',
                                         validators=[
                                             InputRequired(), Length(min=8, max=50)
                                         ])
    submit = SubmitField('Update')


class DeleteProfileForm(FlaskForm):
    password = PasswordField('Password',
                             validators=[
                                 InputRequired(),
                                 Length(min=8, max=50),
                                 EqualTo('confirm_password',
                                         'Passwords must match.')
                             ])
    confirm_password = PasswordField('Confirm Password',
                                     validators=[
                                         InputRequired(), Length(min=8, max=50)
                                     ])
    submit = SubmitField('Delete')


class UploadForm(FlaskForm):
    image = FileField('Upload Image',
                      validators=[InputRequired(), FileAllowed(['jpg', 'png', 'jpeg'])])
    submit = SubmitField('Upload')

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from datetime import datetime
from flask import flash, redirect, render_template, request, Response, url_for
from flask_login import current_user, login_required, logout_user
from PIL import Image
from uuid import uuid4

from app import bcrypt, db
from app.main import bp
from app.main.forms import EditAvatarForm, EditUsernameForm, EditPasswordForm, DeleteProfileForm, UploadForm
from app.models import User, Upload


@bp.route('/')
def index():
    return redirect(url_for('main.home'))


@bp.route('/home')
def home():
    page = request.args.get('page', 1, type=int)
    uploads = Upload.query.order_by(
        Upload.creation_date.desc()).paginate(page=page, per_page=10)
    return render_template('main/home.html', uploads=uploads)


@bp.route('/profile')
@login_required
def profile():
    return redirect(url_for('main.users', username=current_user.username))

@bp.route('/users/<username>')
def users(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username,
                                is_active=True).first_or_404()
    uploads = Upload.query.filter_by(user_id=user.id).order_by(
        Upload.creation_date.desc()).paginate(page=page, per_page=10)
    return render_template('main/user.html', user=user, uploads=uploads)


@bp.route('/profile/avatar/edit', methods=['GET', 'POST'])
@login_required
def edit_avatar():
    form = EditAvatarForm()
    if form.validate_on_submit():
        avatar = Image.open(form.avatar.data)
        if avatar.width == avatar.height:
            uuid = uuid4()
            complete_path = f'app/static/avatars/{uuid}.jpg'
            path = f'avatars/{uuid}.jpg'
            avatar.save(complete_path)
            current_user.avatar = path
            db.session.commit()
            flash('Avatar updated', 'success')
            return Response(status=200)
        else:
            flash('Invalid avatar dimensions', 'danger')
            return Response(status=400)
    return render_template('main/edit_avatar.html', form=form)


@bp.route('/profile/username/edit', methods=['GET', 'POST'])
@login_required
def edit_username():
    form = EditUsernameForm()
    if form.validate_on_submit():
        if current_user.username != form.username.data:
            current_user.username = form.username.data
            db.session.commit()
            flash('Username updated', 'success')
        return redirect(url_for('main.users', username=current_user.username))
    form.username.data = current_user.username
    return render_template('main/edit_username.html', form=form)


@bp.route('/profile/password/edit', methods=['GET', 'POST'])
@login_required
def edit_password():
    form = EditPasswordForm()
    if form.validate_on_submit():
        if bcrypt.check_password_hash(current_user.password, form.password.data):
            current_user.password = bcrypt.generate_password_hash(
                form.new_password.data)
            db.session.commit()
            flash('Password updated', 'success')
            return redirect(url_for('main.users', username=current_user.username))
        else:
            flash('Invalid Password', 'danger')
    return render_template('main/edit_password.html', form=form)


@bp.route('/profile/delete', methods=['GET', 'POST'])
@login_required
def delete_profile():
    form = DeleteProfileForm()
    if form.validate_on_submit():
        if bcrypt.check_password_hash(current_user.password, form.password.data):
            current_user.is_active = False
            db.session.commit()
            logout_user()
            flash('Profile deleted', 'success')
            return redirect(url_for('main.home'))
        else:
            flash('Invalid password', 'danger')
    return render_template('main/delete_profile.html', form=form)


@bp.route('/upload', methods=['GET', 'POST'])
@login_required
def upload():
    form = UploadForm()
    if form.validate_on_submit():
        image = Image.open(form.image.data)
        if image.width == image.height:
            uuid = uuid4()
            complete_path = f'app/static/images/{uuid}.jpg'
            path = f'images/{uuid}.jpg'
            image.save(complete_path)
            upload = Upload(
                image=path, creation_date=datetime.now(), user_id=current_user.id)
            db.session.add(upload)
            db.session.commit()
            flash('Image uploaded', 'success')
            return Response(status=200)
        else:
            flash('Invalid image dimensions', 'danger')
            return Response(status=400)
    return render_template('main/upload.html', form=form)

app/templates/main/delete_profile.html
{% from "render_field.html" import render_field %}
{% extends "base.html" %}
{% block content %}
<h1>Delete Profile</h1>
<form method="POST" action="">
    {{ form.csrf_token }}
    {{ render_field(form.password) }}
    {{ render_field(form.confirm_password) }}
    {{ form.submit(class="btn btn-dark")}}
</form>
{% endblock content %}

app/templates/main/edit_avatar.html
{% from "render_field.html" import render_field %}
{% extends "base.html" %}
{% block content %}
<h1>Edit Avatar</h1>
<form method="POST" enctype="multipart/form-data">
    {{ form.csrf_token }}
    {{ render_field(form.avatar, class='form-control-file') }}
    <div id="croppie-container"></div>
    {{ form.submit(class="btn btn-dark")}}
</form>
{% endblock content %}

{% block scripts %}
<script>
    var form = document.getElementsByTagName('form')[0];

    form.avatar.onchange = function (event) {

        var file = document.querySelector('input[type=file]').files[0];
        var reader = new FileReader();

        if (file.type.match('image.*')) {
            form.querySelector('.form-group').className = 'd-none';
            alert = document.querySelector('.alert');
            if (alert) {
                alert.className = 'd-none';
            }

            reader.addEventListener("load", function () {
                var croppieContainer = document.getElementById('croppie-container');

                var croppie = new Croppie(croppieContainer, {
                    boundary: { width: '30vw', height: '30vw' },
                    viewport: { width: 200, height: 200, type: 'circle' }
                });

                croppie.bind({
                    url: reader.result
                });

                form.addEventListener('submit', function (event) {
                    event.preventDefault();
                    croppie.result({
                        type: 'blob',
                        size: { width: 1024 },
                        format: 'jpeg',
                        circle: false
                    }).then(function (blob) {
                        var formData = new FormData(form);
                        formData.set('avatar', blob, formData.get('avatar').name);
                        var request = new XMLHttpRequest();
                        request.open('POST', '', true);
                        request.onload = function (event) {
                            if (request.status == 200) {
                                window.location = '/profile';
                            } else {
                                window.location = '';
                            }
                        };
                        request.send(formData);
                    });
                }, false);
            });

            reader.readAsDataURL(file);

        } else {
            form.submit.click();
        }
    };
</script>
{% endblock scripts %}

app/templates/main/edit_password.html
{% from "render_field.html" import render_field %}
{% extends "base.html" %}
{% block content %}
<h1>Edit Password</h1>
<form method="POST" action="">
    {{ form.csrf_token }}
    {{ render_field(form.password) }}
    {{ render_field(form.new_password) }}
    {{ render_field(form.confirm_new_password) }}
    {{ form.submit(class="btn btn-dark")}}
</form>
{% endblock content %}

app/templates/main/edit_username.html
{% from "render_field.html" import render_field %}
{% extends "base.html" %}
{% block content %}
<h1>Edit Username</h1>
<form method="POST" action="">
    {{ form.csrf_token }}
    {{ render_field(form.username) }}
    {{ form.submit(class="btn btn-dark")}}
</form>
{% endblock content %}

app/templates/main/home.html
{% extends "base.html" %}

{% from 'render_pagination.html' import render_pagination %}

{% block content %}
<div class="row">
    <div class="d-none d-md-flex">
        <div class="col-md-6">
            {% for upload in uploads.items %}
            {% if loop.cycle(0, 1) == 0 %}
            <p class="text-center mb-0"><small>
                    {% if upload.uploaded_by.is_active %}
                    <a
                        href="{{ url_for('main.users', username=upload.uploaded_by.username) }}">{{ upload.uploaded_by.username }}</a>
                    {% else %}
                    <span class="text-muted">{{ upload.uploaded_by.username }}</span>
                    {% endif %}
                </small></p>
            <img src="{{ url_for('static', filename=upload.image) }}" width="100%">
            <p class="text-center text-muted"><small>{{ upload.creation_date.date() }}</small></p>
            {% endif %}
            {% endfor %}
        </div>

        <div class="col-md-6">
            {% for upload in uploads.items %}
            {% if loop.cycle(0, 1) == 1 %}
            <p class="text-center mb-0"><small>
                    {% if upload.uploaded_by.is_active %}
                    <a
                        href="{{ url_for('main.users', username=upload.uploaded_by.username) }}">{{ upload.uploaded_by.username }}</a>
                    {% else %}
                    <span class="text-muted">{{ upload.uploaded_by.username }}</span>
                    {% endif %}
                </small></p>
            <img src="{{ url_for('static', filename=upload.image) }}" width="100%">
            <p class="text-center text-muted"><small>{{ upload.creation_date.date() }}</small></p>
            {% endif %}
            {% endfor %}
        </div>
    </div>

    <div class="d-md-none">
        <div class="col-md-6">
            {% for upload in uploads.items %}
            <p class="text-center mb-0"><small>
                    {% if upload.uploaded_by.is_active %}
                    <a
                        href="{{ url_for('main.users', username=upload.uploaded_by.username) }}">{{ upload.uploaded_by.username }}</a>
                    {% else %}
                    <span class="text-muted">{{ upload.uploaded_by.username }}</span>
                    {% endif %}
                </small></p>
            <img src="{{ url_for('static', filename=upload.image) }}" width="100%">
            <p class="text-center text-muted"><small>{{ upload.creation_date.date() }}</small></p>
            {% endfor %}
        </div>
    </div>
</div>

{{ render_pagination('main.home', uploads) }}
{% endblock content %}

app/templates/main/upload.html
{% from "render_field.html" import render_field %}
{% extends "base.html" %}
{% block content %}
<h1>Upload</h1>
<form method="POST" enctype="multipart/form-data">
    {{ form.csrf_token }}
    {{ render_field(form.image, class='form-control-file') }}
    <div id="croppie-container"></div>
    {{ form.submit(class="btn btn-dark")}}
</form>
{% endblock content %}

{% block scripts %}
<script>
    var form = document.getElementsByTagName('form')[0];

    form.image.onchange = function (event) {

        var file = document.querySelector('input[type=file]').files[0];
        var reader = new FileReader();

        if (file.type.match('image.*')) {
            form.querySelector('.form-group').className = 'd-none';
            alert = document.querySelector('.alert');
            if (alert) {
                alert.className = 'd-none';
            }

            reader.addEventListener("load", function () {
                var croppieContainer = document.getElementById('croppie-container');

                var croppie = new Croppie(croppieContainer, {
                    boundary: { width: '30vw', height: '30vw' },
                    viewport: { width: 200, height: 200, type: 'square' }
                });

                croppie.bind({
                    url: reader.result
                });

                form.addEventListener('submit', function (event) {
                    event.preventDefault();
                    croppie.result({
                        type: 'blob',
                        size: { width: 1024 },
                        format: 'jpeg'
                    }).then(function (blob) {
                        var formData = new FormData(form);
                        formData.set('image', blob, formData.get('image').name);
                        var request = new XMLHttpRequest();
                        request.open('POST', '', true);
                        request.onload = function (event) {
                            if (request.status == 200) {
                                window.location = 'home';
                            } else {
                                window.location = '';
                            }
                        };
                        request.send(formData);
                    });
                }, false);
            });

            reader.readAsDataURL(file);

        } else {
            form.submit.click();
        }
    };
</script>
{% endblock scripts %}

app/templates/main/user.html
{% extends "base.html" %}
{% from 'render_pagination.html' import render_pagination %}

{% block content %}
<div class="col-xs-1 mb-3" align="center">
    <img src="{{ url_for('static', filename=user.avatar) }}" class="rounded-circle" width="150px">
    <h6 class="mb-0 mt-1">{{ user.username }}</h6>
    <p class="mb-0 text-muted"><small>Member since {{ user.creation_date.date() }}</small></p>
    {% if current_user == user %}
        <p class="mb-0"><small><a href="{{ url_for('main.edit_avatar') }}">Edit Avatar</a></small></p>
        <p class="mb-0"><small><a href="{{ url_for('main.edit_username') }}">Edit Username</a></small></p>
        <p class="mb-0"><small><a href="{{ url_for('main.edit_password') }}">Edit Password</a></small></p>
        <p class="mb-0"><small><a href="{{ url_for('main.delete_profile') }}">Delete Profile</a></small></p>
    {% endif %}
</div>
<div class="row">
        <div class="d-none d-md-flex">
            <div class="col-md-6">
                {% for upload in uploads.items %}
                {% if loop.cycle(0, 1) == 0 %}
                <img src="{{ url_for('static', filename=upload.image) }}" width="100%">
                <p class="text-center text-muted"><small>{{ upload.creation_date.date() }}</small></p>
                {% endif %}
                {% endfor %}
            </div>
    
            <div class="col-md-6">
                {% for upload in uploads.items %}
                {% if loop.cycle(0, 1) == 1 %}
                <img src="{{ url_for('static', filename=upload.image) }}" width="100%">
                <p class="text-center text-muted"><small>{{ upload.creation_date.date() }}</small></p>
                {% endif %}
                {% endfor %}
            </div>
        </div>
    
        <div class="d-md-none">
            <div class="col-md-6">
                {% for upload in uploads.items %}
                <img src="{{ url_for('static', filename=upload.image) }}" width="100%">
                <p class="text-center text-muted"><small>{{ upload.creation_date.date() }}</small></p>
                {% endfor %}
            </div>
        </div>
    </div>
    
    {{ render_pagination('main.users', uploads, username=user.username) }}
{% endblock content %}